version: '3'
services:
   app:
     build: .
     ports:
       - 9000:9000
     depends_on:
       - db
     restart: on-failure
     environment:
       - DATABASE_HOST=db
     volumes:
       - .:/app/src
   db:
     image: mysql:5.7
     ports:
        - 3666:3306
     environment:
        - MYSQL_DATABASE=pintekid
        - MYSQL_ROOT_PASSWORD=@root
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=@root
        - DATABASE_HOST=db